name: Process summary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    name: Process summary
    runs-on: macos-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests BeautifulSoup4 pandas numpy==1.19.5 requests==2.25.1 fpdf2==2.0.6 PyPDF2==1.26.0 pdfplumber==0.5.25 urllib3==1.26.2
        brew install freetype imagemagick
    - name: Build Summary
      run: |
        python3 update_patient.py
        python3 calc_patient.py
        python3 update_mmy.py
        python3 update_isg.py
        python3 update_alert_level.py
        python3 update_military_us.py
        python3 update_vrs.py
        python3 update_sideeffect.py
        python3 update_oka.py
    - name: Commit files
      run: |
        git config --local user.email "ube@coder.okinawa.jp"
        git config --local user.name "Tomoyuki UBE"
        git add csv
        git add data
        git add pdf
        git add component
        git add snapshot
        git add archive
        git diff-index --quiet HEAD || git commit -m "[BOT] Update summary"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}